spring:
  application:
    name: barrier-maintenance-report-hub

  datasource:
    url: jdbc:postgresql://localhost:5432/barrier_report
    username: local_user
    password: local_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-in-milliseconds: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}